pretrain: QMugs
benchmark:
  - DRD2
  - FactorXA
  - Lipo
  - FreeSolv
  - ESOL
  - Efflux
  - Human_CLint
  - Human_PPB
  - Rat_CLint
  - Rat_PPB
  - Solu
  - MUV466
  - MUV548
  - MUV600
  - MUV644
  - MUV652
  - MUV689
  - MUV692
  - MUV712
  - MUV713
  # - MUV733 skip due to issue with no true vals in one of hp folds
  - MUV737
  - MUV810
  - MUV832
  - MUV846
  - MUV852
  - MUV858
  - MUV859
  - NR_AR
  - NR_AR_LBD
  - NR_AhR
  - NR_Aromatase
  - NR_ER
  - NR_ER_LBD
  - NR_PPAR_gamma
  - SR_ARE
  - SR_ATAD5
  - SR_HSE
  - SR_MMP
  - SR_p53