SklearnGIN:
  model_kwargs:
    verbose: False
    epochs: 50
    act: hardswish
    batch_size: 32
    input_dim: 1
  model_hyperparameters:
    tuning: True
    trials: 50
    num_splits: 5
    node_embedding_dim:
      target: categorical
      choices:
        - 4
        - 8
        - 16
        - 32
        - 64
    hidden_dim:
      target: categorical
      choices:
        - 4
        - 8
        - 16
        - 32
        - 64
    gnn_layers:
      target: int
      low: 1
      high: 5
    head_layers:
      target: int
      low: 1
      high: 5
    share_weights:
      target: categorical
      choices:
        - True
        - False
    dropout:
      target: float
      low: 0.0
      high: 0.5
    lr:
      target: float
      low: 0.00001
      high: 0.1
      log: True
    lr_half_life:
      target: float
      low: 5
      high: 50
