experiment: scratch_mtg0
model: SklearnGIN
neptune: true
process: benchmark
tokenizer: MorganGraphTokenizer
tokenizer_kwargs:
  transform_kwargs: {
    max_vocab_size: 128,
    radius: 1,
    chirality: True
  }
verbose: true