experiment: scratch_atom_type
model: SklearnGIN
neptune: true
process: benchmark
featurizer: AtomGraphFeaturizer
featurizer_kwargs:
  transform_kwargs: {}
verbose: true
benchmark:
  - DRD2
  - FactorXA