experiment: scratch_atom_type
model: SklearnGIN
neptune: true
process: benchmark
tokenizer: AtomGraphTokenizer
tokenizer_kwargs:
  transform_kwargs: {}
verbose: true
benchmark:
  - Lipo
  - FreeSolv
  - ESOL