model: LGBM
process: benchmark
benchmark: all
featurizer: PreTrainedFeaturizer
extra_transform_kwargs: {}
neptune: True
verbose: True
featurizer_kwargs:
    transform_kwargs:
        path: False
        layer_pool_type: concat
        gnn: True