process: preprocess
verbose: True
morgan:
  radius: 2
  chirality: True
  fpsize: 2048
standardizer:
  sanitize: True
  fragment_parent: True
  neutralize: True
  reionize: False
  canonical_tautomer: True
  keep_chirality: True
pretrain: QMugs
benchmark:
  - Efflux
  - Human_CLint
  - Human_PPB
  - Rat_CLint
  - Rat_PPB
  - Solu
  - DRD2
  - FactorXA
  - Lipo
  - FreeSolv
  - ESOL
  - MUV466
  - MUV548
  - MUV600
  - MUV644
  - MUV652
  - MUV689
  - MUV692
  - MUV712
  - MUV713
  - MUV733
  - MUV737
  - MUV810
  - MUV832
  - MUV846
  - MUV852
  - MUV858
  - MUV859
  - NR_AR
  - NR_AR_LBD
  - NR_AhR
  - NR_Aromatase
  - NR_ER
  - NR_ER_LBD
  - NR_PPAR_gamma
  - SR_ARE
  - SR_ATAD5
  - SR_HSE
  - SR_MMP
  - SR_p53
filter_threshold: 0.5
splitting:
  kind: butina
  params:
    repeats: 3
    kfolds: 5
    threshold: 0.65

