process: pretrain
experiment: vocab_size
raw_name: pt_gin_radius_2
featurizer_kwargs:
  max_vocab_size: 2048
  radius: 2
  chirality: True
targets:
  ECFP:
    transform_kwargs:
      fpsize: 2048
      radius: 2
      chirality: True
