process: pretrain_autoencoder
pretrain_data: QMugs
experiment: autoencoder
splits:
  - tanimoto_filter_0.5
verbose: True
featurizer: ECFP
featurizer_kwargs:
  fpsize: 2048
  radius: 2
  chirality: True
model: AutoEncoder
AutoEncoder:
  model_kwargs:
    class_weights: True
    hidden_dim: 512
    latent_dim: 256
    encoder_layers: 4
    decoder_layers: 4
    dropout: 0.2
    act: hardswish
    batch_norm: False
    decoder_type: binary
targets:
  ECFP:
    transform_kwargs:
      fpsize: 2048
      radius: 2
      chirality: True
warmup_epochs: 2
lr_decay_half_life: 5
batch_size: 128
epochs: 50
logging: True