experiment: scratch_morgan_graph_radius_0
model: SklearnGIN
logging: false
process: benchmark
featurizer: MorganGraphFeaturizer
featurizer_kwargs:
  transform_kwargs: {
    max_vocab_size: 32,
    radius: 0,
    chirality: True
  }
verbose: true
benchmark:
  - Human_CLint
  - Rat_CLint
  - Human_PPB
  - Rat_PPB
  - Efflux
  - Solu
