process: benchmark
verbose: True
logging: True
model: LGBM
name: pt_gin_benchmark_example
featurizer: PreTrainedFeaturizer
featurizer_kwargs:
    path: False
    layer_pool_type: concat
benchmark:
    - Rat_PPB
num_splits: 25
LGBM:
  model_kwargs:
    verbose: -1
    n_jobs: -1
  model_hyperparameters:
    tuning: False
